cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

custom_admin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.custom_admin, name='custom_admin'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:product_id>/',
         views.edit_product, name='edit_product'),
    path('products/delete/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:category_id>/',
         views.edit_category, name='edit_category'),
    path('categories/delete/<int:category_id>/',
         views.delete_category, name='delete_category'),
    path('brands/add/', views.add_brand, name='add_brand'),
    path('brands/edit/<int:brand_id>/', views.edit_brand, name='edit_brand'),
    path('brands/delete/<int:brand_id>/',
         views.delete_brand, name='delete_brand'),
]

infinity_innovations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404
from profiles.views import track_order_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('custom_admin/', include('custom_admin.urls')),
    path('api/track/<str:tracking_number>/', track_order_api, name='track_order_api'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'infinity_innovations.views.handler404'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products,
         name='products', kwargs={'universe': 'all'}),
    path('real/', views.all_products,
         name='real_products', kwargs={'universe': 'real'}),
    path('digital/', views.all_products,
         name='digital_products', kwargs={'universe': 'digital'}),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

products/models.py
from django.db import models


class Category(models.Model):
    """ Category model """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254)
    universe = models.CharField(max_length=254, default='real')

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Brand(models.Model):
    """ Brand model """
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254)
    universe = models.CharField(max_length=254, default='real')

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    """ Product model """
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(
        'Brand', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_themes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
            max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

custom_admin/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from products.models import Product, Category, Brand


class ProductForm(forms.ModelForm):
    """
    Class for the product form model
    """
    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        c_friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        brands = Brand.objects.all()
        b_friendly_names = [(b.id, b.get_friendly_name()) for b in brands]

        self.fields['category'].choices = c_friendly_names
        self.fields['brand'].choices = b_friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form-field'


class CategoryForm(forms.ModelForm):
    """
    Class for the category form model
    """
    class Meta:
        model = Category
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        universes = [('real', 'Real'), ('digital', 'Digital')]

        self.fields['universe'] = forms.ChoiceField(
                choices=universes, widget=forms.Select)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form-field'


class BrandForm(forms.ModelForm):
    """
    Class for the brand form model
    """
    class Meta:
        model = Brand
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        universes = [('real', 'Real'), ('digital', 'Digital')]

        self.fields['universe'] = forms.ChoiceField(
            choices=universes, widget=forms.Select)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form-field'

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, Brand


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        c_friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        brands = Brand.objects.all()
        b_friendly_names = [(b.id, b.get_friendly_name()) for b in brands]

        self.fields['category'].choices = c_friendly_names
        self.fields['brand'].choices = b_friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'product-form-field'

custom_admin/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
import os
from django.contrib import messages
from .forms import ProductForm, CategoryForm, BrandForm
from django.contrib.auth.decorators import login_required
from products.models import Product, Category, Brand
from profiles.models import UserProfile


@login_required
def custom_admin(request):
    """A view to render the custom admin page"""

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can enter this page')
        return redirect(reverse('home'))

    return render(request, 'custom_admin/custom_admin.html')


@login_required
def add_product(request):
    """ Add a product to the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can add products')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')

    else:
        form = ProductForm()

    template = 'products/add_product.html'

    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can edit products')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.')

    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'

    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can delete products')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')

    return redirect(reverse('products'))


@login_required
def add_category(request):
    """ Add a category to the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can add categories')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added category!')
            return redirect(reverse('custom_admin'))
        else:
            messages.error(
                request,
                'Failed to add category. Please ensure the form is valid.')

    else:
        form = CategoryForm()

    template = 'categories/add_category.html'

    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_category(request, category_id):
    """ Edit a category in the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can edit categories')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated category!')
            return redirect(reverse('custom_admin'))
        else:
            messages.error(
                request,
                'Failed to update category. Please ensure the form is valid.')

    else:
        form = CategoryForm(instance=category)
        messages.info(request, f'You are editing {category.name}')

    template = 'categories/edit_category.html'

    context = {
        'form': form,
        'category': category,
    }

    return render(request, template, context)


@login_required
def delete_category(request, category_id):
    """ Delete a category from the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can delete categories')
        return redirect(reverse('home'))

    category = get_object_or_404(Category, pk=category_id)
    category.delete()
    messages.success(request, 'Category deleted!')

    return redirect(reverse('custom_admin'))


@login_required
def add_brand(request):
    """ Add a brand to the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can add brands')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added brand!')
            return redirect(reverse('custom_admin'))
        else:
            messages.error(
                request,
                'Failed to add brand. Please ensure the form is valid.')

    else:
        form = BrandForm()

    template = 'brands/add_brand.html'

    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_brand(request, brand_id):
    """ Edit a brand in the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can edit brands')
        return redirect(reverse('home'))

    brand = get_object_or_404(Brand, pk=brand_id)

    if request.method == 'POST':
        form = BrandForm(request.POST, instance=brand)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated brand!')
            return redirect(reverse('custom_admin'))
        else:
            messages.error(
                request,
                'Failed to update brand. Please ensure the form is valid.')

    else:
        form = BrandForm(instance=brand)
        messages.info(request, f'You are editing {brand.name}')

    template = 'brands/edit_brand.html'

    context = {
        'form': form,
        'brand': brand,
    }

    return render(request, template, context)


@login_required
def delete_brand(request, brand_id):
    """ Delete a brand from the store """

    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only admins can delete categories')
        return redirect(reverse('home'))

    brand = get_object_or_404(Brand, pk=brand_id)
    brand.delete()
    messages.success(request, 'Brand deleted!')

    return redirect(reverse('custom_admin'))

products/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse
from django.db.models.functions import Lower
from .models import Product, Category, Brand


def all_products(request, universe):
    """ A view to show all products, including sorting and search queries """
    current_universe = 'all'
    if universe == 'real':
        products = Product.objects.filter(category__universe='real')
        current_universe = 'real'
    elif universe == 'digital':
        products = Product.objects.filter(category__universe='digital')
        current_universe = 'digital'
    elif universe == 'all':
        products = Product.objects.all()
    else:
        return HttpResponse("Invalid type parameter")
    query = None
    categories = None
    sort = None
    direction = None
    brands = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if sortkey == 'category':
                sortkey = 'category__name'

            if sortkey == 'brand':
                sortkey = 'brand__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'

            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'brand' in request.GET:
            brands = request.GET['brand'].split(',')
            products = products.filter(brand__name__in=brands)
            brands = Brand.objects.filter(name__in=brands)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter an search criteria!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'
    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'current_universe': current_universe,
        'current_brands': brands,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)

custom_admin/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/custom_admin.css' %}">
{% endblock %}

{% block content %}

<section class="add-product-section section">
    <div class="add-product-section-container section-container container-col">
        <h2 class="add-product-section-heading dark-text">Product Management</h2>
        <div class="add-product-section-subheading dark-text">Add a Product</div>
        <div class="add-product-form-container container-col">

            <form action="{% url 'add_product' %}" method="POST" class="add-product-form container-col" id="payment-form" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Category</p>
                    <label for="id_category" class="sr-only">category</label>
                    {{ form.category }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Brand</p>
                    <label for="id_brand" class="sr-only">brand</label>
                    {{ form.brand }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Sku</p>
                    <label for="id_sku" class="sr-only">sku</label>
                    {{ form.sku }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Name</p>
                    <label for="id_name" class="sr-only">Name</label>
                    {{ form.name }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Description</p>
                    <label for="id_description" class="sr-only">description</label>
                    {{ form.description }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Has Themes</p>
                    <label for="id_has_themes" class="sr-only">has_themes</label>
                    {{ form.has_themes }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Price</p>
                    <label for="id_price" class="sr-only">price</label>
                    {{ form.price }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Rating</p>
                    <label for="id_rating" class="sr-only">rating</label>
                    {{ form.rating }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Image Url</p>
                    <label for="id_image_url" class="sr-only">image_url</label>
                    {{ form.image_url }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Image</p>
                    <label for="id_image" class="sr-only">image</label>
                    {{ form.image }}
                </div>

                <div class="add-product-form-btns-container container-row">
                    <a href="{% url 'custom_admin' %}" class="cancel-btn btn">
                        <span class="fa-icon"><i class="fa-solid fa-chevron-left"></i></span>
                        Cancel
                    </a>
                    <button type="submit" class="btn add-product-submit-btn">
                        <span class="fa-icon"><i class="fa-solid fa-circle-plus"></i></span>
                        Add Product
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script src="{% static 'js/product-management.js' %}"></script>
{% endblock %}

custom_admin/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/custom_admin.css' %}">
{% endblock %}

{% block content %}

<section class="add-product-section section">
    <div class="add-product-section-container section-container container-col">
        <h2 class="add-product-section-heading dark-text">Product Management</h2>
        <div class="add-product-section-subheading dark-text">Edit a Product</div>
        <div class="add-product-form-container container-col">

            <form action="{% url 'edit_product' product.id %}" method="POST" class="add-product-form container-col" id="payment-form" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Category</p>
                    <label for="id_category" class="sr-only">category</label>
                    {{ form.category }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Brand</p>
                    <label for="id_brand" class="sr-only">brand</label>
                    {{ form.brand }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Sku</p>
                    <label for="id_sku" class="sr-only">sku</label>
                    {{ form.sku }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Name</p>
                    <label for="id_name" class="sr-only">Name</label>
                    {{ form.name }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Description</p>
                    <label for="id_description" class="sr-only">description</label>
                    {{ form.description }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Has Themes</p>
                    <label for="id_has_themes" class="sr-only">has_themes</label>
                    {{ form.has_themes }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Price</p>
                    <label for="id_price" class="sr-only">price</label>
                    {{ form.price }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Rating</p>
                    <label for="id_rating" class="sr-only">rating</label>
                    {{ form.rating }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Image Url</p>
                    <label for="id_image_url" class="sr-only">image_url</label>
                    {{ form.image_url }}
                </div>
                <div class="add-product-form-input-container container-col">
                    <p class="dark-text">Image</p>
                    <label for="id_image" class="sr-only">image</label>
                    {{ form.image }}
                </div>


                <div class="add-product-form-btns-container container-row">
                    <a href="{% url 'products' %}" class="cancel-btn btn">
                        <span class="fa-icon"><i class="fa-solid fa-chevron-left"></i></span>
                        Cancel
                    </a>
                    <button type="submit" class="btn add-product-submit-btn">
                        <span class="fa-icon"><i class="fa-solid fa-pen-to-square"></i></span>
                        Edit Product
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script src="{% static 'js/product-management.js' %}"></script>
{% endblock %}