cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.contact, name='contact'),
]

infinity_innovations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404
from profiles.views import track_order_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('custom_admin/', include('custom_admin.urls')),
    path('api/track/<str:tracking_number>/', track_order_api, name='track_order_api'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'infinity_innovations.views.handler404'

contact/models.py
from django.db import models


class ContactMessage(models.Model):
    """
    Contact message model
    """
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import ContactMessage


class ContactForm(forms.ModelForm):
    """
    Class for the Contact form model
    """
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']

contact/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
import os
from django.contrib import messages

from .forms import ContactForm


def contact(request):
    """A view to render the contact page"""

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            send_contact_email(form.cleaned_data)
            messages.success(request, 'Your message has been sent, Thank you')
            return redirect('home')
    else:
        form = ContactForm()

    context = {
        'form': form,
    }

    return render(request, 'contact/contact.html', context)


def send_contact_email(data):
    """
    Send a contact email
    """
    subject = 'New Contact Message'
    message = f"Name: {data['name']}\nEmail: "\
              f"{data['email']}\n\n{data['message']}"
    from_email = os.environ.get('EMAIL_HOST_USER')
    to_email = [os.environ.get('EMAIL_HOST_USER')]
    send_mail(subject, message, from_email, to_email)

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock %}

{% block content %}
<section class="section contact-section">
    <div class="contact-section-container section-container container-row">
        <form action="{% url 'contact' %}" class="contact-form container-col" method="POST">
            {% csrf_token %}
            <div class="contact-form-input-container container-col">
                <div class="dark-text">Name</div>
                <label for="id_name" class="sr-only">name input</label>
                {{ form.name }}
            </div>
            <div class="contact-form-input-container container-col">
                <div class="dark-text">Email</div>
                <label for="id_email" class="sr-only">email input</label>
                {{ form.email }}
            </div>
            <div class="contact-form-input-container container-col">
                <label for="id_message" class="sr-only">message input</label>
                <div class="dark-text">Message</div>
                {{ form.message}}
            </div>
            <button type="submit" class="contact-form-submit-btn btn">Send</button>
        </form>

        <div class="contact-info-container container-col">
            <h3 class="dark-text">Contact Us</h3>
            <div class="dark-text">Please get in contact with us if you have any questions and need help:</div>
            <div class="contact-info-text dark-text">infinityinnovationsinfo@gmail.com</div>
            <div class="contact-info-text dark-text">(555) 555-5555</div>
            <div class="social-media-container container-col">
                <p class="dark-text">Follow Us on Social Media</p>
                <a href="https://www.facebook.com/profile.php?id=61552186373211&is_tour_dismissed=true" target="_blank" class="dark-text">
                    <span class="fa-icon"><i class="fa-brands fa-facebook"></i></span>
                    Facebook
                </a>
                <a href="https://www.instagram.com/infinityinnovationsvr/" target="_blank" class="dark-text">
                    <span class="fa-icon"><i class="fa-brands fa-instagram"></i></span>
                    Instagram
                </a>
            </div>
            <div class="newsletter-container container-col">
                <div id="mc_embed_signup">
                    <form target="_blank" action="https://herokuapp.us11.list-manage.com/subscribe/post?u=bf25b2e2a322f9f212f4e1b4f&amp;id=119fec0438&amp;f_id=0054ace0f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate container-col" novalidate="">
                        <div id="mc_embed_signup_scroll" class="mc-form-container container-col"><p class="dark-text">Join Our Newsletter</p>
                            <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                            <div class="mc-field-group mc-form-container container-col">
                                <label for="mce-EMAIL" class="sr-only">Newsletter input</label>
                                <input type="email" name="EMAIL" class="required email mc-input" id="mce-EMAIL" placeholder="Email" required="" value="">
                            </div>
                        <div id="mce-responses" class="clear foot">
                            <div class="response" id="mce-error-response" style="display: none;"></div>
                            <div class="response" id="mce-success-response" style="display: none;"></div>
                        </div>
                        <div aria-hidden="true" style="position: absolute; left: -5000px;">
                            /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
                            <label for="mc-hidden-input" class="sr-only">Newsletter input</label>
                            <input type="text" name="b_bf25b2e2a322f9f212f4e1b4f_119fec0438" tabindex="-1" value="" id="mc-hidden-input">
                        </div>
                            <div class="optionalParent">
                                <div class="clear foot">
                                    <label for="mc-embedded-subscribe" class="sr-only">Newsletter input</label>
                                    <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn" value="Subscribe" name="mc-embedded-subscribe">
                                    <p style="margin: 0px auto;"><a href="http://eepurl.com/iA1WiQ" title="Mailchimp - email marketing made easy and fun"><span style="display: inline-block; background-color: transparent; border-radius: 4px;"><img class="refferal_badge" src="https://digitalasset.intuit.com/render/content/dam/intuit/mc-fe/en_us/images/intuit-mc-rewards-text-dark.svg" alt="Intuit Mailchimp" style="width: 220px; height: 40px; display: flex; padding: 2px 0px; justify-content: center; align-items: center;"></span></a></p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}